In [246]:
# Importing the libraries
import pandas as pd 
import numpy as np

Since We have 2 datasets clean , fix , visualize both datasets before concatenation

## DataSet 1 : Dubizzle from scraping

In [247]:
df1 = pd.read_csv("dubizzle_egypt_cars.csv")
dub = df1.copy()
dub.head()

,listing_id,url,listed_date,title,make,model,version,year,kilometers,price,...,transmission,fuel_type,body_type,exterior_color,condition,payment_options,location,price_type,is_verified,attributes_json
0,h7302649,https://www.dubizzle.com.eg/en/ad/used-mercede...,2026-10-12,Used Mercedes B 150 2007 For Sale Alexandria,Mercedes-Benz,B150,NaN,2007,100000,1000.0,...,Automatic,Benzine,Hatchback,Black,Used,NaN,Alexandria,price,False,"[{""name"": ""Brand"", ""value"": ""Mercedes-Benz""}, ..."
1,h7303192,https://www.dubizzle.com.eg/en/ad/imported-use...,2026-10-13,Imported Used Hyundai Avante 2014 For Sale Cairo,Hyundai,Avante,NaN,2014,106000,1000.0,...,Automatic,Diesel,Sedan,Silver,Used,NaN,Cairo,price,False,"[{""name"": ""Brand"", ""value"": ""Hyundai""}, {""name..."
2,h7296860,https://www.dubizzle.com.eg/en/ad/used-isuzu-d...,2026-10-03,Used Isuzu D max 2015 For Sale Kafr el-Sheikh,Isuzu,D-Max,NaN,2015,100000,15000.0,...,Manual,Diesel,Pickup,White,Used,NaN,Kafr al-Sheikh,price,False,"[{""name"": ""Brand"", ""value"": ""Isuzu""}, {""name"":..."
3,185410949,https://www.dubizzle.com.eg/en/ad/%D8%B4%D8%B1...,2026-10-04,شراء سيارات خردة,Fiat,Other,NaN,1980,25000,18000.0,...,Manual,Benzine,Other,Other Color,Used,Cash,"Tanta, Gharbia",price,False,"[{""name"": ""Brand"", ""value"": ""Fiat""}, {""name"": ..."
4,209174949,https://www.dubizzle.com.eg/en/ad/%D9%81%D9%8A...,2026-10-07,فيات 132 1976,Fiat,132,NaN,1976,100000,22000.0,...,Manual,Benzine,Sedan,Silver,Used,Cash,"Alam Al- Rum, Marsa Matrouh, Matruh",price,False,"[{""name"": ""Brand"", ""value"": ""Fiat""}, {""name"": ..."

In [248]:
dub.info() #--> 13190 x 21

<class 'pandas.DataFrame'>
RangeIndex: 13190 entries, 0 to 13189
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   listing_id       13190 non-null  str
 1   url              13190 non-null  str
 2   listed_date      13190 non-null  str
 3   title            13190 non-null  str
 4   make             13190 non-null  str
 5   model            13190 non-null  str
 6   version          5278 non-null   str
 7   year             13190 non-null  int64
 8   kilometers       13190 non-null  int64
 9   price            13190 non-null  float64
 10  currency         13190 non-null  str
 11  transmission     13190 non-null  str
 12  fuel_type        13190 non-null  str
 13  body_type        13181 non-null  str
 14  exterior_color   13190 non-null  str
 15  condition        13190 non-null  str
 16  payment_options  10139 non-null  str
 17  location         13190 non-null  str
 18  price_type       13190 non-null  str
 19  is_verified      13190 non-null  bool
 20  attributes_json  13190 non-null  str
dtypes: bool(1), float64(1), int64(2), str(17)
memory usage: 17.0 MB

In [249]:
dub.describe()

               year    kilometers         price
count  13190.000000  1.319000e+04  1.319000e+04
mean    2014.771190  1.336886e+05  1.623812e+06
std       11.902832  1.237703e+06  2.296336e+06
min     1951.000000  0.000000e+00  1.000000e+03
25%     2008.000000  9.800000e+03  3.000000e+05
50%     2019.000000  9.300000e+04  8.600000e+05
75%     2024.000000  1.840000e+05  1.925000e+06
max     2027.000000  1.000000e+08  5.150000e+07

In [250]:
dub.isna().sum()

listing_id            0
url                   0
listed_date           0
title                 0
make                  0
model                 0
version            7912
year                  0
kilometers            0
price                 0
currency              0
transmission          0
fuel_type             0
body_type             9
exterior_color        0
condition             0
payment_options    3051
location              0
price_type            0
is_verified           0
attributes_json       0
dtype: int64

In [251]:
dub = dub.drop_duplicates().reset_index(drop=True)
dub = dub.drop(columns=[ "listed_date" , "location" , "attributes_json" , "currency"])

In [252]:
print(dub.columns.to_list())

['listing_id', 'url', 'title', 'make', 'model', 'version', 'year', 'kilometers', 'price', 'transmission', 'fuel_type', 'body_type', 'exterior_color', 'condition', 'payment_options', 'price_type', 'is_verified']

Fixing noise in columns

In [253]:
dub["title"].sample(5) # not much of a help + same as the make and model but also has arabic typing

9581              Volkswagen Passat Comfort | Model 2022
132                Used Fiat Regata 1987 For Sale Helwan
5893                               شيفروليه كابتيفا 2020
11604    BMW 320i 2026 New Version | خصم عن السعر الرسمي
2062                                    دايو نوبيرا 1997
Name: title, dtype: str

In [254]:
dub = dub.drop(columns="title")

In [255]:
print(dub["make"].dropna().unique().tolist())

['Mercedes-Benz', 'Hyundai', 'Isuzu', 'Fiat', 'Jeep', 'Volkswagen', 'Peugeot', 'Mazda', 'Lada', 'Nissan', 'Skoda', 'Suzuki', 'Seat', 'Citroen', 'Renault', 'Ford', 'Honda', 'Chevrolet', 'Changhe', 'Daihatsu', 'Changan', 'Aito', 'BMW', 'Mitsubishi', 'Geely', 'Kia', 'Volvo', 'Daewoo', 'Buick', 'Toyota', 'Lifan', 'BYD', 'Opel', 'Chery', 'Speranza', 'Subaru', 'Proton', 'Lancia', 'Great Wall', 'Chana', 'Saipa', 'Brilliance', 'Chrysler', 'Alfa Romeo', 'Zotye', 'Faw', 'Smart', 'Audi', 'Ssang Yong', 'Jac', 'Foton', 'Karry', 'Land Rover', 'Mahindra', 'Soueast', 'DFSK', 'Senova', 'Baic', 'Perodua', 'GMC', 'Hafei', 'Haima', 'MG', 'Jaguar', 'Hawtai', 'Other make', 'MINI', 'Shineray', 'KYC', 'Jetour', 'Ds', 'Dongfeng', 'Kaiyi', 'Bestune', 'Haval', 'King Long', 'Arcfox', 'Maserati', 'GAC', 'Lincoln', 'Domy', 'Lotus', 'Forthing', 'Porsche', 'Dodge', 'Exeed', 'Lynk & Co', 'XPeng', 'Tesla', 'Cupra', 'Deepal', 'KGM', 'Hongqi', 'ICAUR', 'Cadillac', 'Avatr', 'Zeekr', 'IM', 'Rehigh', 'Abarth', 'Xiaomi', 'Genesis', 'ROX', 'Li Auto', 'M-Hero', 'Bentley', 'Hummer', 'Lexus', 'Maextro', 'Aston Martin', 'Lamborghini', 'Ferrari', 'Rolls Royce']

In [256]:
dub["model"].unique()

<ArrowStringArray>
[          'B150',         'Avante',          'D-Max',          'Other',
            '132', 'Grand Cherokee',            '128',         'Beetle',
           '1100',           '1300',
 ...
    'Flying Spur',           'Urus',     'GranCabrio',           'Roma',
             'XM',           'S580',        'Huracan',       'Cullinan',
        'Spectre',       'S 63 AMG']
Length: 917, dtype: str

In [257]:
dub["version"].unique() # not useful

<ArrowStringArray>
[                                         nan,
                                          '1',
                                      'بيتلز',
                                     'الماني',
                                       '1970',
                                       '1100',
                                         '82',
                                       '1989',
                                        'نصر',
                                       '1977',
 ...
                                    'Maybach',
                          'SV Long 2024 P615',
                              'MERCEDES BENZ',
                   'LAMBORGHINI HURACÁN EVO ',
                      'Mercedes Maybach S580',
              'Mercedes-Maybach S580 4MATIC ',
                                  'Speed w12',
                                        'Evo',
        'ONe*ONe Mercedes S63 AMG BRABUS 930',
 'Rolls-Royce Cullinan Black Badge Series II']
Length: 3244, dtype: str

In [258]:
dub = dub.drop(columns="version")

In [259]:
dub["transmission"].unique()

<ArrowStringArray>
['Automatic', 'Manual']
Length: 2, dtype: str

In [260]:
dub["fuel_type"].unique()

<ArrowStringArray>
['Benzine', 'Diesel', 'Electric', 'Natural Gas', 'Hybrid']
Length: 5, dtype: str

In [261]:
dub["body_type"].unique()

<ArrowStringArray>
[     'Hatchback',          'Sedan',         'Pickup',          'Other',
            'MPV', 'Sports / Coupe',            'SUV',              nan,
         'Estate',      'Van / Bus',            '4X4', 'Small city car',
    'Convertible']
Length: 13, dtype: str

In [262]:
dub["body_type"].value_counts(dropna=False) # nulls will be filled in the pipeline

body_type
Sedan             6526
SUV               4263
Hatchback         1740
Sports / Coupe     220
Van / Bus          143
Pickup             112
MPV                 90
Convertible         71
NaN                  9
4X4                  9
Estate               5
Other                1
Small city car       1
Name: count, dtype: int64

In [263]:
dub = dub[~dub["body_type"].isin([ "Other" , "Small city car"])] # not useful

In [264]:
dub["exterior_color"].value_counts()

exterior_color
Black              3080
Gray               2312
White              1934
Blue- Navy Blue    1576
Silver             1562
Red                 979
Burgundy            474
Green               424
Gold                314
Brown               195
Other Color         128
Beige               104
Yellow               56
Orange               50
Name: count, dtype: int64

In [265]:
dub["condition"].unique()

<ArrowStringArray>
['Used', 'New']
Length: 2, dtype: str

In [266]:
dub["payment_options"].unique() # # nulls will be filled in the pipeline

<ArrowStringArray>
[nan, 'Cash', 'Exchange', 'Cash or Installment', 'Installments']
Length: 5, dtype: str

In [267]:
dub["price_type"].unique() # any price is negotioble

<ArrowStringArray>
['price', 'arranged']
Length: 2, dtype: str

In [268]:
dub = dub.drop(columns="price_type")

In [269]:
dub["is_verified"].value_counts() # verified by dubizzle , could be helpful so leave it

is_verified
False    7809
True     5379
Name: count, dtype: int64

In [270]:
dub = dub.drop(columns = "is_verified")

In [271]:
print(dub.columns.to_list())

['listing_id', 'url', 'make', 'model', 'year', 'kilometers', 'price', 'transmission', 'fuel_type', 'body_type', 'exterior_color', 'condition', 'payment_options']

## DataSet 2 : for Kaggle

In [272]:
df2 = pd.read_csv("egypt_used_cars1.csv")
kagg = df2.copy()
kagg.head()

,listing_id,url,title,brand,model,year,mileage_km,transmission,fuel,price_egp,...,is_premium,body_shape,engine,color,imported,in_warranty,dealer_id,seller,scraped_at,source
0,7260774,https://eg.hatla2ee.com/en/car/bmw/x5/7260774,BMW X5 2023,BMW,X5,2023.0,23000.0,Automatic,Gas,4800000,...,False,NaN,NaN,NaN,False,False,NaN,NaN,2026-08-08T22:34:36,hatla2ee
1,7260825,https://eg.hatla2ee.com/en/car/bmw/x3/7260825,BMW X3 2023,BMW,X3,2023.0,23000.0,Automatic,Diesel,3500000,...,False,NaN,NaN,NaN,False,False,NaN,NaN,2026-08-08T22:34:36,hatla2ee
2,7231253,https://eg.hatla2ee.com/en/car/bmw/x1/7231253,BMW X1 2025,BMW,X1,2025.0,6000.0,Automatic,Gas,2950000,...,False,NaN,NaN,NaN,False,False,NaN,NaN,2026-08-08T22:34:36,hatla2ee
3,7261887,https://eg.hatla2ee.com/en/car/bmw/320/7261887,BMW 320 2020,BMW,320,2020.0,110000.0,Automatic,Gas,1900000,...,True,NaN,NaN,NaN,False,False,NaN,NaN,2026-08-08T22:34:36,hatla2ee
4,7246713,https://eg.hatla2ee.com/en/car/bmw/320/7246713,BMW 320 2023,BMW,320,2023.0,70000.0,Automatic,Gas,2600000,...,True,NaN,NaN,NaN,False,False,NaN,NaN,2026-08-08T22:34:36,hatla2ee

In [273]:
kagg.info() # 24856 x 21

<class 'pandas.DataFrame'>
RangeIndex: 24857 entries, 0 to 24856
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   listing_id    24857 non-null  str
 1   url           24857 non-null  str
 2   title         24857 non-null  str
 3   brand         24857 non-null  str
 4   model         24829 non-null  str
 5   year          24855 non-null  float64
 6   mileage_km    24836 non-null  float64
 7   transmission  24856 non-null  str
 8   fuel          24735 non-null  str
 9   price_egp     24857 non-null  int64
 10  location      24857 non-null  str
 11  is_premium    24857 non-null  bool
 12  body_shape    6526 non-null   str
 13  engine        6493 non-null   str
 14  color         6575 non-null   str
 15  imported      24857 non-null  bool
 16  in_warranty   24857 non-null  bool
 17  dealer_id     6615 non-null   float64
 18  seller        1722 non-null   str
 19  scraped_at    24857 non-null  str
 20  source        24857 non-null  str
dtypes: bool(3), float64(3), int64(1), str(14)
memory usage: 7.6 MB

In [274]:
kagg.describe()

               year    mileage_km     price_egp     dealer_id
count  24855.000000  2.483600e+04  2.485700e+04  6.615000e+03
mean    2013.659183  1.381735e+05  1.176809e+06  2.781068e+06
std       10.074120  1.265506e+05  1.646265e+06  5.412807e+05
min     1965.000000  0.000000e+00  5.000000e+03  4.340000e+02
25%     2008.000000  4.500000e+04  3.500000e+05  2.533510e+06
50%     2016.000000  1.200000e+05  6.650000e+05  3.094343e+06
75%     2021.000000  2.000000e+05  1.250000e+06  3.120710e+06
max     2027.000000  2.000000e+06  4.400000e+07  3.145211e+06

In [275]:
kagg.isna().sum()

listing_id          0
url                 0
title               0
brand               0
model              28
year                2
mileage_km         21
transmission        1
fuel              122
price_egp           0
location            0
is_premium          0
body_shape      18331
engine          18364
color           18282
imported            0
in_warranty         0
dealer_id       18242
seller          23135
scraped_at          0
source              0
dtype: int64

In [276]:
kagg = kagg.drop_duplicates().reset_index()
kagg = kagg.drop(columns = ["scraped_at" , "seller" , "in_warranty" , "imported" , "is_premium" , "location" , "title" , "dealer_id"])

In [277]:
print(kagg.columns.to_list())

['index', 'listing_id', 'url', 'brand', 'model', 'year', 'mileage_km', 'transmission', 'fuel', 'price_egp', 'body_shape', 'engine', 'color', 'source']

fixing noise

In [278]:
kagg = kagg.drop(columns="index")

In [279]:
kagg["brand"].unique()

<ArrowStringArray>
[         'BMW',          'BYD',     'Cadillac',        'Chery',
    'Chevrolet',       'Daewoo',         'Fiat',      'Hyundai',
          'Kia',   'Land Rover',
 ...
        'Lexus',        'Exeed',       'Hongqi',       'Lancia',
 'Aston Martin',        'Buick',       'Deepal',        'Hafei',
      'Perodua',           'IM']
Length: 107, dtype: str

In [280]:
brands = [
    'Mercedes-Benz', 'Hyundai', 'Isuzu', 'Fiat', 'Jeep',
    'Volkswagen', 'Peugeot', 'Mazda', 'Lada', 'Nissan',
    'Skoda', 'Suzuki', 'Seat', 'Citroen', 'Renault', 'Ford',
    'Honda', 'Chevrolet', 'Changhe', 'Daihatsu', 'Changan',
    'Aito', 'BMW', 'Mitsubishi', 'Geely', 'Kia', 'Volvo',
    'Daewoo', 'Buick', 'Toyota', 'Lifan', 'BYD', 'Opel',
    'Chery', 'Speranza', 'Subaru', 'Proton', 'Lancia',
    'Great Wall', 'Chana', 'Saipa', 'Brilliance', 'Chrysler',
    'Alfa Romeo', 'Zotye', 'Faw', 'Smart', 'Audi',
    'Ssang Yong', 'Jac', 'Foton', 'Karry', 'Land Rover',
    'Mahindra', 'Soueast', 'DFSK', 'Senova', 'Baic',
    'Perodua', 'GMC', 'Hafei', 'Haima', 'MG', 'Jaguar',
    'Hawtai', 'Other make', 'MINI', 'Shineray', 'KYC',
    'Jetour', 'Ds', 'Dongfeng', 'Kaiyi', 'Bestune', 'Haval',
    'King Long', 'Arcfox', 'Maserati', 'GAC', 'Lincoln',
    'Domy', 'Lotus', 'Forthing', 'Porsche', 'Dodge', 'Exeed',
    'Lynk & Co', 'XPeng', 'Tesla', 'Cupra', 'Deepal', 'KGM',
    'Hongqi', 'ICAUR', 'Cadillac', 'Avatr', 'Zeekr', 'IM',
    'Rehigh', 'Abarth', 'Xiaomi', 'Genesis', 'ROX', 'Li Auto',
    'M-Hero', 'Bentley', 'Hummer', 'Lexus', 'Maextro',
    'Aston Martin', 'Lamborghini', 'Ferrari', 'Rolls Royce'
]

kagg = kagg[kagg["brand"].isin(brands)].copy()

In [281]:
kagg["brand"].unique()

<ArrowStringArray>
[          'BMW',           'BYD',      'Cadillac',         'Chery',
     'Chevrolet',        'Daewoo',          'Fiat',       'Hyundai',
           'Kia',    'Land Rover',     'Lynk & Co', 'Mercedes-Benz',
    'Mitsubishi',            'MG',        'Nissan',          'Opel',
       'Peugeot',       'Renault',         'Skoda',        'Suzuki',
        'Toyota',    'Volkswagen',         'Zeekr',           'KYC',
    'Alfa Romeo',          'Audi',         'Avatr',       'Bentley',
       'Bestune',    'Brilliance',         'Chana',       'Changan',
       'Changhe',      'Chrysler',       'Citroen',         'Cupra',
          'DFSK',      'Daihatsu',         'Dodge',      'Dongfeng',
           'Faw',          'Ford',      'Forthing',           'GAC',
           'GMC',         'Geely',    'Great Wall',         'Haima',
         'Haval',        'Hawtai',         'Honda',        'Hummer',
         'Isuzu',        'Jaguar',          'Jeep',        'Jetour',
           'KGM',         'Kaiyi',          'Lada',   'Lamborghini',
       'Li Auto',         'Lifan',       'Lincoln',         'Lotus',
      'Mahindra',      'Maserati',         'Mazda',          'MINI',
       'Porsche',        'Proton',           'ROX',   'Rolls Royce',
         'Saipa',          'Seat',        'Senova',      'Shineray',
       'Soueast',      'Speranza',        'Subaru',         'Tesla',
         'Volvo',         'XPeng',         'Zotye',        'Xiaomi',
         'Karry',         'Lexus',         'Exeed',        'Hongqi',
        'Lancia',  'Aston Martin',         'Buick',        'Deepal',
         'Hafei',       'Perodua',            'IM']
Length: 95, dtype: str

In [282]:
kagg["model"].unique()

<ArrowStringArray>
[            'X5',             'X3',             'X1',            '320',
            '520',             'XM',             'X6',            '750',
             'M4',             'X2',
 ...
             'Fc', 'Grand Wagoneer',         'Ascona',           'C280',
             'G6',        'Tiggo 5',     'Destinator',         '207 SW',
           '2111',           '300D']
Length: 1161, dtype: str

In [283]:
kagg["fuel"].unique()

<ArrowStringArray>
['Gas', 'Diesel', 'Hybrid', 'Natural Gas', 'Electric', 'Plug-in Hybrid', nan]
Length: 7, dtype: str

In [284]:
kagg["fuel"] = kagg["fuel"].replace("Gas", "Benzine")
kagg["fuel"] = kagg["fuel"].replace("Plug-in Hybrid", "Hybrid")

In [285]:
kagg["fuel"].unique()

<ArrowStringArray>
['Benzine', 'Diesel', 'Hybrid', 'Natural Gas', 'Electric', nan]
Length: 6, dtype: str

In [286]:
kagg["body_shape"].unique() # 18k+ null

<ArrowStringArray>
[        nan, 'Hatchback',     'Coupe',     'Sedan',       'SUV', 'Cabriolet',
       'Van',    'Pickup',   'Station']
Length: 9, dtype: str

In [287]:
kagg["body_shape"] = kagg["body_shape"].replace("Coupe" , "Sports / Coupe" )
kagg["body_shape"] = kagg["body_shape"].replace("Van" , "Van / Bus" )

In [288]:
kagg['body_shape'] = kagg.body_shape.replace({'Cabriolet': 'Convertible', 'Station': 'Estate'})

In [289]:
kagg["engine"].unique()

<ArrowStringArray>
[                               nan,                            'Other',
                      '1.4 A/T F/O',              '2.0 A/T Turbo Super',
                             '1400',                             '1600',
                             '2000',                    '2.0 A/T Super',
                      '1.8 A/T F/O',                             '1500',
 ...
                  '1.6 A/T Metalic',                   '1.6 A/T C-Plus',
 '2.0T T6 AWD Momentum (7- seater)', '2.0 A/T Inscription  (New Shape)',
             '2.0 A/T Ins  7 Seats',    '2.0 A/T R-Design  (New Shape)',
                   '2.0 A/T C-Plus',         '2.0 A/T Ins  5 Seats 4WD',
               'RWD Long Range R21',        'RWD Long Range With Nappa']
Length: 976, dtype: str

In [290]:
kagg = kagg.drop(columns = "engine")

In [291]:
kagg["color"].value_counts() # 18k+ null

color
Black        1356
Gray          944
White         825
Silver        817
Blue          481
Red           455
Maroon        301
Navy Blue     290
Dark Grey     215
Brown         134
Green         130
Baby Blue     118
Gold          112
Champagne      69
Bronze         57
Beige          55
Turquoise      34
Purple         17
Name: count, dtype: int64

In [292]:
kagg["color"] = kagg["color"].replace("Blue" , "Blue- Navy Blue")
kagg["color"] = kagg["color"].replace("Navy Blue" , "Blue- Navy Blue")

In [293]:
print(kagg.columns.tolist())

['listing_id', 'url', 'brand', 'model', 'year', 'mileage_km', 'transmission', 'fuel', 'price_egp', 'body_shape', 'color', 'source']

In [294]:
kagg = kagg.rename(columns={
    'brand':      'make',
    'mileage_km': 'kilometers',
    'price_egp':  'price',
    'fuel':       'fuel_type',
    'body_shape': 'body_type',
    'color':      'exterior_color',
})

In [295]:
kagg["transmission"].unique()

<ArrowStringArray>
['Automatic', 'Manual', nan, 'Dual Clutch', 'CVT', 'XTRONIC CVT']
Length: 6, dtype: str

In [296]:
kagg['transmission'] = kagg.transmission.replace(
    {'Dual Clutch': 'Automatic', 'CVT': 'Automatic', 'XTRONIC CVT': 'Automatic'})

In [297]:
print(kagg.columns.tolist())

['listing_id', 'url', 'make', 'model', 'year', 'kilometers', 'transmission', 'fuel_type', 'price', 'body_type', 'exterior_color', 'source']

In [298]:
kagg["source"].unique()

<ArrowStringArray>
['hatla2ee', 'contactcars', 'dubizzle']
Length: 3, dtype: str

In [299]:
dub["source"] = "dubizzle" # adding this column for future plans as deployment
print(dub.columns.tolist())

['listing_id', 'url', 'make', 'model', 'year', 'kilometers', 'price', 'transmission', 'fuel_type', 'body_type', 'exterior_color', 'condition', 'payment_options', 'source']

In [300]:
dub.groupby("condition")["kilometers"].mean()

condition
New          0.282546
Used    163966.743141
Name: kilometers, dtype: float64

In [301]:
is_new = (kagg.kilometers <= 100) & (kagg.year >= 2025)
kagg['condition'] = is_new.map({True: 'New', False: 'Used'})
kagg.loc[kagg.kilometers.isna(), 'condition'] = pd.NA

In [302]:
kagg.condition.value_counts(normalize=True)

condition
Used    0.998741
New     0.001259
Name: proportion, dtype: float64

In [303]:
dub.condition.value_counts(normalize=True)

condition
Used    0.815362
New     0.184638
Name: proportion, dtype: float64

In [304]:
kagg["payment_options"] = np.nan

In [305]:
kagg = kagg[~kagg.listing_id.isin(dub.listing_id)]

In [306]:
kagg.to_csv("kagg_cleaned.csv", index=False)
dub.to_csv("dub_cleaned.csv" , index=False)

## Concat both datasets into one large dataset!

In [307]:
df = pd.concat([dub, kagg[dub.columns]], ignore_index=True)

In [308]:
# Save into a CSV file
df.to_csv("Egypt_Used_Cars.csv")